### ISSUE TITLE
STAGE

### ISSUE THREAD

**Issue by Edzgarl** [Tristan-Guerro/Discussion#2]
Alors Tristan, c'est good aujourd'hui ?

**Comment by Tristan-Guerro** [comment]
Oula

**Comment by Tristan-Guerro** [comment]
Pas foufou on va dire

**Comment by Edzgarl** [comment]
C'est quand ta réu ?

**Comment by Tristan-Guerro** [comment]
je sais pas mais je vais me faire goumer

**Comment by Tristan-Guerro** [comment]
oula on fait ça tout a l'heure 
Alors ya rien qui fonctionne en plus depuis la dernière fois

**Comment by Edzgarl** [comment]
Ah merde, bah y'a des complications de toute façon
T'étais absent puis bon, la méthode agile hein

**Comment by Lapastoure** [comment]
Hello

**Comment by Tristan-Guerro** [comment]
ouai ahah méthode agile

**Comment by Lapastoure** [comment]
Alors comme ça vous créé des issues sans prévenir

**Comment by Edzgarl** [comment]
C'était pour pas discuter dans "18h Guinness" mdr

**Comment by Lapastoure** [comment]
Je suis sous l'eau je comprends rien au code de l'autre stagiaire on est là quoi

**Comment by Lapastoure** [comment]
![Screenshot_20200204-132317](https://user-images.githubusercontent.com/33086290/73747871-a0482c00-4758-11ea-80f1-bd98a444a0f4.jpg)

**Comment by Edzgarl** [comment]
Enculé

**Comment by Lapastoure** [comment]
👀👀

**Comment by Lapastoure** [comment]
Mon programme met 5 minutes avant de crash 😭

**Comment by Edzgarl** [comment]
Le code su stagiaire est codé avec les pieds ou quoi ?

**Comment by Tristan-Guerro** [comment]
Ben moi j'avance pas
C'est terrible

**Comment by Lapastoure** [comment]
Non justement c'est bien fait même trop je pige rien

**Comment by Tristan-Guerro** [comment]
terrible

**Comment by Lapastoure** [comment]
@Edzgarl issou

**Comment by Lapastoure** [comment]
j'ai supp le message je vais me faire grillé sinon ahaha

**Comment by Edzgarl** [comment]
Tu es né où @Tristan-Guerro ?

**Comment by Tristan-Guerro** [comment]
je parlais a l'expert node

**Comment by Tristan-Guerro** [comment]
je me retrouve a faire du C#

**Comment by Tristan-Guerro** [comment]
jsuis en pls 
INTERGALACTIQUE

**Comment by Edzgarl** [comment]
Mdr terrible

**Comment by Tristan-Guerro** [comment]
###  Tavernier un verre a boire !

**Comment by Lapastoure** [comment]
Aled

**Comment by Lapastoure** [comment]
![15808392117053788483298977784929](https://user-images.githubusercontent.com/33086290/73772555-a0f4b880-4780-11ea-96e9-860b1eac2d74.jpg)

**Comment by Tristan-Guerro** [comment]
je suis pas bien devant visual studio...

**Comment by Lapastoure** [comment]
Vous parlez chinois ? 
moi pas : 
Traceback (most recent call last):
  File "CheckReference.py", line 6, in <module>
    process.launcher(sys.argv)
  File "/home/CDWEB/admin.clapastoure/Travail_referentiel/src/Process.py", line 88, in launcher
    self._process_global()
  File "/home/CDWEB/admin.clapastoure/Travail_referentiel/src/Process.py", line 108, in _process_global
    self.ctools.process(self.dictionnary)
  File "/home/CDWEB/admin.clapastoure/Travail_referentiel/src/Ctools.py", line 116, in process
    self._treatment(dictionnary,dico,line,result)
  File "/home/CDWEB/admin.clapastoure/Travail_referentiel/src/Ctools.py", line 98, in _treatment
    self.utility.update_dictionnary(dictionnary[result['ip']][0],'CTOOLS', 'True')
IndexError: list index out of range

**Comment by Tristan-Guerro** [comment]
je doit faire un appel api jsuis duper

**Comment by Tristan-Guerro** [comment]
c'est sur swagger
ça a l'air horriblement naze

**Comment by Lapastoure** [comment]
Api je peux t'aider j'ai fais depuis le début du stage

**Comment by Lapastoure** [comment]
je suis champion appel api en python

**Comment by Tristan-Guerro** [comment]
moi c avec react

**Comment by Lapastoure** [comment]
en vrai envoie tes code d'erreur comme moi

**Comment by Tristan-Guerro** [comment]
quand tu fais un json parse tu peux directement parse l'url qui renvoi le json ?

**Comment by Tristan-Guerro** [comment]
en gros voila l'url de mon APi : 

`https://localhost:44391/swagger/docs/v1``

apres je parse mais j'ai le droit de faire ça ? : 

`var` obj = JSON.parse(API_URI);

**Comment by Tristan-Guerro** [comment]
API_URI c'est mon nom de var de l'url au cas ou

**Comment by Lapastoure** [comment]
de mémoire json parse tu parse la réponse

**Comment by Lapastoure** [comment]
wtf pk tu fais ça ?

**Comment by Lapastoure** [comment]
`def _auth(self):
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
        authentification_request = requests.Request('POST', self._url + 'user/', auth=(self._username, self._password))
        authent_request = authentification_request.prepare()
        authentification = self.session_to_use.send(authent_request)

        if authentification.status_code != 200:
            self.utility.display_error('authentification ' + str(authentification.status_code))

        # get token of the user
        try:
            self._token_ipam = authentification.json()['data']['token']
        except json.JSONDecodeError as e:
            self.utility.display_error('loading json for the token',e)`

c'est  du python mais la je fais un appel api si le code c'est 200 (don cok)
je parse pour recup le token

**Comment by Tristan-Guerro** [comment]
c en local moi 
ça renvoi pas de token

**Comment by Tristan-Guerro** [comment]
mais c swagger
ça me full duper son bail

**Comment by Lapastoure** [comment]
https://developer.mozilla.org/fr/docs/Learn/JavaScript/Objects/JSON

**Comment by Lapastoure** [comment]
après si ton api est ok elle renvoi forcement des infos, essaie de print le code genre 404 ou 200 et le body ou header de la réponse

**Comment by Lapastoure** [comment]
https://www.w3schools.com/js/js_json_parse.asp

var xmlhttp = new XMLHttpRequest();
xmlhttp.onreadystatechange = function() {
  if (this.readyState == 4 && this.status == 200) {
    var myObj = JSON.parse(this.responseText);
    document.getElementById("demo").innerHTML = myObj.name;
  }
};
xmlhttp.open("GET", "json_demo.txt", true);
xmlhttp.send();

**Comment by Tristan-Guerro** [comment]
en gros il me file ça comme info

**Comment by Tristan-Guerro** [comment]
![image](https://user-images.githubusercontent.com/33086546/73856028-29cd2c00-4835-11ea-9247-0d4d2cbf7674.png)

**Comment by Tristan-Guerro** [comment]
ah putain jcrois je commençe a capter

**Comment by Lapastoure** [comment]
bg ta requet est ok code 200

**Comment by Tristan-Guerro** [comment]
putain jsuis retard

**Comment by Lapastoure** [comment]
il te reste plus qu'a stocké ton body dans une variable et de parse

**Comment by Lapastoure** [comment]
enfin si tu veux récupérer le user

**Comment by Tristan-Guerro** [comment]
apres jcapte pas comment je fais ça sur react

**Comment by Tristan-Guerro** [comment]
je suis obligé de créer un fichier json ?
ou je peux direct faire ça en ligne ?

**Comment by Lapastoure** [comment]
après j'ai du mal à comprendre tu as crée une api en local ?

**Comment by Tristan-Guerro** [comment]
nop c un truc pour visualiser

**Comment by Tristan-Guerro** [comment]
mon api elle est sur visual studio

**Comment by Edzgarl** [comment]
Je suis perdu rien qu'à lire tout ça mdr

**Comment by Lapastoure** [comment]
tu as forcement un code ou un fichier (json xml txt) derrière les données ne sorte pas de nul part

**Comment by Lapastoure** [comment]
envoie le code de ton api

**Comment by Lapastoure** [comment]
oups

**Comment by Tristan-Guerro** [comment]
ben elle sortent de la bdd

**Comment by Tristan-Guerro** [comment]
ben ya 30 classes donc bon

**Comment by Lapastoure** [comment]
ah

**Comment by Lapastoure** [comment]
bah le api/log/0 y'a quoi derrière ?

**Comment by Tristan-Guerro** [comment]
![image](https://user-images.githubusercontent.com/33086546/73856753-3dc55d80-4836-11ea-87da-8a9d47dfa01a.png)

**Comment by Lapastoure** [comment]
bah le principe de l'api tu crée un sorte de route ou tu appel un id qui contient des data

**Comment by Tristan-Guerro** [comment]
normlement c ça

**Comment by Lapastoure** [comment]
ok je vois un peu mieux

**Comment by Lapastoure** [comment]
essaie un appel avec curl mais remplace le 0 par 4 par exemple

**Comment by Tristan-Guerro** [comment]
en gros swagger c comme postman sauf que tu peux le custom pour mieux visualiser tes requetes

**Comment by Lapastoure** [comment]
sinon tu as fiddler après chacun ses gout

**Comment by Tristan-Guerro** [comment]
mais du coup jsuis paumé
je sais pas quoi faire sur react la

**Comment by Lapastoure** [comment]
je pense tristan le bail tu as du mal a comprendre le bail derrière l'url regarde un tuto simple de creation d'api en C#

**Comment by Lapastoure** [comment]
Tu sais faire un appel api en js ?

**Comment by Lapastoure** [comment]
un code simple d'un get 

var request = new XMLHttpRequest()

// Open a new connection, using the GET request on the URL endpoint
request.open('GET', 'https://ghibliapi.herokuapp.com/films', true)

request.onload = function() {
  // Begin accessing JSON data here
}

// Send request
request.send()

**Comment by Tristan-Guerro** [comment]
ouai c'est ce que j'ai dans mon code

**Comment by Lapastoure** [comment]
https://www.taniarascia.com/how-to-connect-to-an-api-with-javascript/

**Comment by Lapastoure** [comment]
bah envoi ton code react

**Comment by Lapastoure** [comment]
tu arrive a print le body ou le code ou le headers depuis react ?

**Comment by Lapastoure** [comment]
Putain mon programme tourne encore il va jamais finir wtf

**Comment by Tristan-Guerro** [comment]
c'est bon jsuis full duper

**Comment by Lapastoure** [comment]
Mais non c'est chaud au debut les api

**Comment by Tristan-Guerro** [comment]
genre j'ai ça

**Comment by Tristan-Guerro** [comment]
![image](https://user-images.githubusercontent.com/33086546/73857913-e45e2e00-4837-11ea-9fdb-a6ef07e5038a.png)

**Comment by Lapastoure** [comment]
C'est quoi l'erreur ?

**Comment by Tristan-Guerro** [comment]
![image](https://user-images.githubusercontent.com/33086546/73857988-0061cf80-4838-11ea-830e-d629193f4bf3.png)

**Comment by Tristan-Guerro** [comment]
ah merde

**Comment by Tristan-Guerro** [comment]
le request open j'ai pas le droit de l'utiliser avec webpack

**Comment by Tristan-Guerro** [comment]
mais du coup jcapte vraiment rien

**Comment by Tristan-Guerro** [comment]
je comprend pas comment appeler cette putain d'api

**Comment by Lapastoure** [comment]
tu as essaie de faire juste un fichier js en dehors de react et d'utiliser l'api ?

**Comment by Lapastoure** [comment]
Tu l'utilises ton header ? j'ai pas l'impression

**Comment by Lapastoure** [comment]
https://stackoverflow.com/questions/247483/http-get-request-in-javascript 

téma stack c'est le s

**Comment by Tristan-Guerro** [comment]
wesh je capte r

**Comment by Lapastoure** [comment]
wesh la détail

**Comment by Lapastoure** [comment]
https://youtu.be/ZEEV7FDM3D8

**Comment by Tristan-Guerro** [comment]
ça rend fou

**Comment by Tristan-Guerro** [comment]
la requete avec postman fonctionne meme pas

**Comment by Tristan-Guerro** [comment]
ça va le rapport ?
